[plot]
dim = [4000, 750]

[first]
n_zscores_collapse = 3.0
n_zscores_misjoin = 3.0
window_size = 1_000_000
bp_merge = 100_000
min_bp_peak = 1

[second]
n_zscores = 3.4
window_size = 500_000
bp_merge = 5000
min_perc = 0.5
min_bp_peak = 1
thr_het_ratio = 0.2
